name:
  Generate ICAL feeds and send to S3
on:
  workflow_dispatch:
  schedule:
    # This runs at 00:00 UTC every day
    - cron: '0 20 * * *'

jobs:
  sync_ical_feeds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: pip install awscli

      - name: Generate ICAL feeds
        run: |
          node export-ics.mjs
          ls
          for f in *.ics; do aws s3 cp "$f" "s3://$AWS_BUCKET_NAME/$f"; done
        env:
          VULCAN_URL: ${{secrets.VULCAN_URL}}
          VULCAN_USERNAME: ${{secrets.VULCAN_USERNAME}}
          VULCAN_PASSWORD: ${{secrets.VULCAN_PASSWORD}}
          VULCAN_SCHOOL_UNIT_ID: ${{secrets.VULCAN_SCHOOL_UNIT_ID}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
          AWS_DEFAULT_REGION: us-east-1
