# This is a basic workflow to help you get started with Actions
 
name:
  Generate ICAL feeds and send to S3
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  workflow_dispatch:  
  schedule:
    - cron: "11 * * * *"
 
jobs:
  sync_ical_feeds:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      # Runs a single command using the runners shell
      - run: pip install vulcan icalendar
      - name: Generate ICAL feeds
        run: |
          pip install icalendar
          echo $VULCAN_ACCOUNT > account.json
          echo $VULCAN_KEYSTORE > keystore.json
          python3 export-ics.py
          ls
          
