name:
  Generate ICAL feeds and send to S3
on:
  workflow_dispatch:  
  schedule:
    - cron: "11 */2 * * *"
 
jobs:
  sync_ical_feeds:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'

      - run: pip install vulcan-api icalendar
      
      - name: Generate ICAL feeds
        run: |
          sudo apt update -qq
          sudo apt install awscli
          echo "$VULCAN_ACCOUNT_JSON" > account.json
          echo "$VULCAN_KEYSTORE_JSON" > keystore.json
          python3 export-ics.py
          ls
          for f in *.ics; do aws s3 cp "$f" "s3://$AWS_BUCKET_NAME/$f"; done
        env:
          VULCAN_ACCOUNT_JSON: ${{secrets.VULCAN_ACCOUNT_JSON}}
          VULCAN_KEYSTORE_JSON: ${{secrets.VULCAN_KEYSTORE_JSON}}
          VULCAN_STUDENT: ${{secrets.VULCAN_STUDENT}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
          AWS_DEFAULT_REGION: us-east-1
          
