# This is a basic workflow to help you get started with Actions
 
name:
  Generate ICAL feeds and send to S3
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  workflow_dispatch:  
  schedule:
    - cron: "11 * * * *"
 
jobs:
  sync_ical_feeds:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      # Runs a single command using the runners shell
      - run: pip install vulcan-api icalendar
      - name: Generate ICAL feeds
        run: |
          sudo apt update -qq
          sudo apt install awscli
          echo "$VULCAN_ACCOUNT_JSON" > account.json
          echo "$VULCAN_KEYSTORE_JSON" > keystore.json
          python3 export-ics.py
          ls
          aws s3 cp *.ics s3://$AWS_BUCKET_NAME/
        env:
          VULCAN_ACCOUNT_JSON: ${{secrets.VULCAN_ACCOUNT_JSON}}
          VULCAN_KEYSTORE_JSON: ${{secrets.VULCAN_KEYSTORE_JSON}}
          VULCAN_STUDENT: ${{secrets.VULCAN_STUDENT}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
          
